//  Vectors
#define BAD_VECTOR_SIZE_EXCEPTION   1
#define VECTOR_LINEAR_DEPENDENT     2


//  Matrix
#define BAD_MATRIX_SIZE_EXCEPTION   100
#define MATRIX_NOT_SQUARE           101
#define MATRNIX_NOT_DIAGONALYZABLE  102